# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`match-simple-XS`
	:runtime-requirement    [ :on "perl 5.008"^^:CpanId ];
	:runtime-recommendation [ :on "match::simple"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

